### ISSUE TITLE
distinct operator should be distinctUntilChanged?

### ISSUE THREAD

**Issue by Wrywulf** [pwittchen/ReactiveBeacons#16]
In ReactiveBeacons.java the distinct() operator is used:

```java
/**
   * Creates an observable stream of BLE beacons, which can be subscribed with RxJava
   *
   * @return Observable stream of beacons
   */
  @SuppressWarnings("deprecation") public Observable<Beacon> observe() {
    leScanCallbackAdapter = new LeScanCallbackAdapter();
    bluetoothAdapter.startLeScan(leScanCallbackAdapter);
    return leScanCallbackAdapter.toObservable().repeat().distinct().doOnUnsubscribe(new Action0() {
      @Override public void call() {
        bluetoothAdapter.stopLeScan(leScanCallbackAdapter);
      }
    });
```
   But because Beacon.java equals():

````java
...
    if (rssi != beacon.rssi) return false;
...
```

This causes any beacon throughout scanning history with identical Rssi levels to _not_ be emitted.

I guess what's really important for proximity detection is to have the latest beacon Rssi value - even if it existed in history already. This could be solved (and at the same time avoiding immediate duplicates) using distinctUntilChanged.

Should I make a PR?

**Comment by pwittchen** [comment]
Hi,

Thank you for creating an issue. I treat each emitted `Beacon` object as a different immutable piece of data. I've added `distinct()` operator to avoid situation in which single `Beacon` will be emitted multiple times to the subscriber even if RSSI of this specific `Beacon` wasn't changed. That's why Bluetooth `Device` object and RSSI value are used in `equals(...)` method in `Beacon` class.

I'm not familiar with `distinctUntilChanged(...)` operator, but I took a quick look at the documentation and I think, you may be right. You can create a PR. I'll test changed Observable in the sample app and if it will behave correctly and there won't be overflow of duplicated data, we can merge it.

**Comment by pwittchen** [comment]
Related PR: #17.

**Comment by pwittchen** [comment]
PR was merged to master branch.
